from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
import time
import json
import os

from software_factory.agents.base import PlannerAgent, BuilderAgent
from software_factory.core.models import ExecutionState, TaskStatus

console = Console()

class DAGOrchestrator:
    """Executes the workflow plan generated by the Planner."""
    
    def __init__(self, output_dir: str):
        self.state = ExecutionState()
        self.planner = PlannerAgent()
        self.builder = BuilderAgent()
        self.output_dir = output_dir
        
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def run(self, goal: str):
        """Main execution loop."""
        
        # 1. Planning Phase
        self.state.plan = self.planner.execute(goal=goal)
        
        # Output plan for Antigravity Agents to read
        plan_path = os.path.join(self.output_dir, "plan.md")
        with open(plan_path, "w") as f:
            f.write(f"# Implementation Plan\n\n**Goal:** {goal}\n\n## Tasks\n")
            for t in self.state.plan.tasks:
                f.write(f"- [ ] **{t.id}**: {t.description} (Deps: {t.dependencies})\n")
        
        console.print(f"[green]Plan written to {plan_path} for Antigravity integration.[/]")
        
        # 2. Execution Phase (Sequential DAG execution for now)
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
        ) as progress:
            
            for task in self.state.plan.tasks:
                task_ui = progress.add_task(f"[cyan]Executing {task.id}:[/] {task.description}", total=None)
                
                # Check dependencies (mock logic)
                for dep in task.dependencies:
                    dep_task = next((t for t in self.state.plan.tasks if t.id == dep), None)
                    if dep_task and dep_task.status != TaskStatus.COMPLETED:
                        console.print(f"[red]Dependency {dep} for {task.id} not completed![/]")
                        task.status = TaskStatus.FAILED
                        progress.stop()
                        return
                        
                task.status = TaskStatus.IN_PROGRESS
                
                # Execute task via builder
                result = self.builder.execute(task, context=self.state.memory)
                task.result = result
                task.status = TaskStatus.COMPLETED
                
                # Update Antigravity UI state tracking
                self.state.memory[task.id] = result
                time.sleep(1) # simulate work
                
                progress.update(task_ui, description=f"[green]Completed {task.id}:[/] {task.description}")
        
        console.print(Panel("[bold green]All tasks completed successfully.[/bold green]"))
